# Generated by Django 4.2.3 on 2023-07-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('passwd', models.CharField(max_length=30)),
                ('fullname', models.CharField(max_length=50)),
                ('datetime', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
